[visualization]
export = true
interval = 1200

[[visualize_agent]]
name = "TumorCell"
additional_data_members = [
  "diameter_",
  "volume_",
  "cell_type_"
]

[[visualize_agent]]
name = "CarTCell"
additional_data_members = ["diameter_","volume_"]

[[visualize_diffusion]]
name = "oxygen"